title:   Avinash Varma
logo: "/Images/Profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Dedicated Analyst with an experience in customer service and client relationship management with an educational background in Marketing management and financial service. Sound knowledge of data manipulation tools with an eye for detail, a strong analytical ability and a real time relative experience with personal projects using various programming tools.  
  <br><br><br>
  <a href="https://https://www.linkedin.com/in/avinash-varma-67aba390//">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br>

  
theme: jekyll-theme-minimal   
 
